apiVersion: v1
kind: Service
metadata:
  name: cloud-sql-cluster-ip-service
spec:
  type: ClusterIP
  clusterIP: 10.88.12.77
  ports:
  - port: 3308
    targetPort: port-cloudsql
  selector:
    app: cloud-sql-proxy