version: "3"
services:
  mysqldb:
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: 'ikea_usecase'
      MYSQL_ROOT_PASSWORD: 'bharathdsce'
    ports:
      - 30000:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  twittertopubsub:
    build:
      context: .
      dockerfile: twitterToPubSub/Dockerfile
#    image: twittertopubsub:latest

  beamrunner:
    build:
      context: .
      dockerfile: beamRunner/Dockerfile
#    image: beamrunner:latest
    links:
      - mysqldb
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - WAIT_HOSTS=mysqldb:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
